"""added username

Revision ID: 2af1ec12556b
Revises: 582893b7e334
Create Date: 2023-04-18 15:05:33.313281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af1ec12556b'
down_revision = '582893b7e334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_trails', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_trails_trail_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_trails_trail_id_trails'), 'trails', ['trail_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    with op.batch_alter_table('user_trails', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_trails_trail_id_trails'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_trails_trail_id_users', 'users', ['trail_id'], ['id'])

    # ### end Alembic commands ###
